"""
StructuredHistorySummary — Domain Schema.

The AI-generated clinical summary that is sent to the doctor for review.

CRITICAL SAFETY REQUIREMENT (AGENTS.md Rule 9):
    Every StructuredHistorySummary:
    - MUST have is_ai_generated = True
    - MUST have requires_physician_review = True

    These fields are not configurable. They are frozen at schema level.
    The service layer enforces this. The API layer exposes them.
    The doctor dashboard displays them prominently.

    An AI-generated summary is NEVER a medical record until a physician
    has reviewed and confirmed it.

    This is not just a convention — it is an architectural invariant of MediKiosk.

AI Architecture:
    The summary is generated by the LLM (deferred to Phase 7+) using the
    structured ClinicalHistory as input. The LLM:
        - Generates a readable narrative from the structured fields
        - Surfaces key clinical findings
        - Highlights red flags prominently
        - Synthesizes document extraction findings

    The LLM does NOT diagnose, prescribe, or make autonomous clinical decisions.

ReviewStatus lifecycle:
    DRAFT → UNDER_REVIEW → REVIEWED   (accepted by physician)
    DRAFT → UNDER_REVIEW → REJECTED   (physician rejects, requests re-elicitation)
"""

import uuid
from datetime import datetime, timezone
from enum import Enum

from pydantic import BaseModel, Field, model_validator


class ReviewStatus(str, Enum):
    """
    Lifecycle status of an AI-generated summary through physician review.

    DRAFT        — Generated by AI, not yet seen by physician
    UNDER_REVIEW — Physician has opened the summary
    REVIEWED     — Physician confirmed and accepted the summary
    REJECTED     — Physician rejected; may trigger re-elicitation
    """

    DRAFT = "draft"
    UNDER_REVIEW = "under_review"
    REVIEWED = "reviewed"
    REJECTED = "rejected"


class StructuredHistorySummary(BaseModel):
    """
    AI-generated clinical history summary for physician review.

    This is ALWAYS an AI-generated draft. It ALWAYS requires physician review.
    These are architectural invariants — see module docstring.
    """

    summary_id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        description="Unique identifier for this summary.",
    )
    session_id: uuid.UUID = Field(
        description="The session this summary was generated for.",
    )
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp when this summary was generated.",
    )

    # ── Safety-Critical Flags ─────────────────────────────────────────────────
    is_ai_generated: bool = Field(
        default=True,
        description=(
            "Always True. This summary was generated with AI assistance. "
            "Attempting to set this to False raises a ValidationError."
        ),
    )
    requires_physician_review: bool = Field(
        default=True,
        description=(
            "Always True. This summary REQUIRES physician review before clinical use. "
            "Attempting to set this to False raises a ValidationError."
        ),
    )

    @model_validator(mode="after")
    def enforce_safety_invariants(self) -> "StructuredHistorySummary":
        """
        Enforce the two core clinical safety invariants:

        1. is_ai_generated must always be True — every summary produced by
           this system is AI-assisted and must be treated as such.
        2. requires_physician_review must always be True — no AI-generated
           summary may bypass physician review.

        These constraints are NOT configurable. Any attempt to construct a
        StructuredHistorySummary with either flag set to False is a
        programming error and will raise a ValidationError.
        """
        if not self.is_ai_generated:
            raise ValueError(
                "is_ai_generated must always be True. "
                "MediKiosk does not support non-AI-generated summaries via this schema."
            )
        if not self.requires_physician_review:
            raise ValueError(
                "requires_physician_review must always be True. "
                "AI-generated summaries must always require physician review before clinical use."
            )
        return self

    # ── Summary Content ────────────────────────────────────────────────────────
    chief_complaint: str = Field(
        description="The patient's chief complaint as summarised.",
    )
    history_narrative: str = Field(
        description=(
            "Readable clinical narrative of the patient's history. "
            "AI-generated from the structured ClinicalHistory. "
            "Must be reviewed and corrected by the physician before use."
        ),
    )
    key_findings: list[str] = Field(
        default_factory=list,
        description="Bulleted key clinical findings extracted from the history.",
    )
    red_flags: list[str] = Field(
        default_factory=list,
        description=(
            "Clinical red flags surfaced during history collection. "
            "Displayed prominently in the doctor dashboard."
        ),
    )
    document_findings: list[str] = Field(
        default_factory=list,
        description="Key findings extracted from uploaded medical documents.",
    )

    # ── Review State ───────────────────────────────────────────────────────────
    review_status: ReviewStatus = Field(
        default=ReviewStatus.DRAFT,
        description="Current physician review status of this summary.",
    )
