"""
SummaryService — Service Protocol.

Defines the interface for AI-generated clinical history summary generation.

CRITICAL SAFETY REQUIREMENT (AGENTS.md Rule 9):
    All summaries generated by this service MUST have:
        is_ai_generated = True
        requires_physician_review = True

    The service MUST NOT create summaries with these fields set to False.
    The StructuredHistorySummary schema enforces this at the type level (frozen fields).

AI Architecture (Phase 7+):
    The generate_summary() method will:
    1. Retrieve the ClinicalHistory for the session
    2. Retrieve any DocumentExtraction results for session documents
    3. Pass both to the LLM (Gemini / Ollama / etc.) with a structured prompt
    4. Validate the LLM output against the StructuredHistorySummary schema
    5. Return the validated, draft summary

    The LLM is NEVER given the ability to set review_status to REVIEWED.
    Only a DoctorReview (submitted by the physician) can advance the status.

Implementation note (Phase 6):
    The Phase 6 stub will return a template-based summary populated from
    the ClinicalHistory fields, with no LLM call. This allows the API to
    be tested end-to-end before the AI layer is built.
"""

import uuid
from typing import Protocol

from app.domain.schemas.summary import StructuredHistorySummary


class SummaryService(Protocol):
    """
    Interface for generating and retrieving AI-generated clinical summaries.
    """

    async def generate_summary(
        self,
        session_id: uuid.UUID,
    ) -> StructuredHistorySummary:
        """
        Generate an AI-assisted clinical history summary for a session.

        Retrieves the session's ClinicalHistory and DocumentExtractions,
        generates a StructuredHistorySummary using the AI layer (Phase 7+),
        and stores the result.

        The returned summary ALWAYS has:
            is_ai_generated = True
            requires_physician_review = True
            review_status = DRAFT

        Args:
            session_id: The session to generate a summary for.

        Returns:
            A new StructuredHistorySummary in DRAFT status.
        Raises:
            SessionNotFoundError: If the session does not exist.
            ConsentRequiredError: If consent has not been given.
            AIProcessingError: If summary generation fails (Phase 7+).
        """
        ...

    async def get_summary(
        self,
        session_id: uuid.UUID,
    ) -> StructuredHistorySummary | None:
        """
        Retrieve the current summary for a session.

        Args:
            session_id: The session to retrieve the summary for.

        Returns:
            The StructuredHistorySummary if generated, None otherwise.
        """
        ...
